### ISSUE TITLE
Modelar cartas de serviços em RDF Schema

### ISSUE THREAD

**Issue by augusto-herrmann** [servicosgovbr/cartas-de-servico#2]
Para que seja possível descrever um serviço em uma página usando RDFa, é necessário dispor de vocabulários para expressar as classes e propriedades. A sugestão é que seja criado um vocabulário de serviços públicos que reflita o modelo de dados utilizado no portal de serviços.

Esse modelo poderia se basear no [Core Public Service Application Profile](https://joinup.ec.europa.eu/asset/cpsv-ap/home) e referenciar, a princípio:
- [Core Public Service Vocabulary](https://joinup.ec.europa.eu/asset/core_public_service/home) (CPSV) - serviço
- [vcard](http://lov.okfn.org/dataset/lov/vocabs/vcard) - informações de contato, endereços
- [Core Organization Ontology](http://lov.okfn.org/dataset/lov/vocabs/org) - órgão público
- [schema.org](http://schema.rdfs.org/) - vários
- [SKOS](http://lov.okfn.org/dataset/lov/vocabs/skos) - assuntos

**Comment by kchnr** [comment]
Cartão do subproduto II.4 da TR correspondente: https://github.com/servicosgovbr/consultoria/issues/11

**Comment by oliviagj** [comment]
@cv, esse aqui conversa com o #447?

**Comment by cv** [comment]
Não exatamente - é um formato de exportação separado, que pode ou não ser embutido no HTML gerado pelas páginas dos serviços.

**Comment by cv** [comment]
Fechando esse cartão - exportar as cartas em RDFa ou outros formatos será feito por cartões no servicosgovbr/portal-de-servicos.
