### ISSUE TITLE
Migrar VCGE para 2.x

### ISSUE THREAD

**Issue by cv** [servicosgovbr/cartas-de-servico#21]
Cartas na v3 deveriam estar no VCGE 2.x, e estão numa versão anterior.

Todos os XMLs devem ser migrados, mas o código dessa migração não precisa viver além do término dessa tarefa.

**Comment by augusto-herrmann** [comment]
Pensando na experiência do usuário, discordo desse cartão.

O VCGE 2.x é muito raso e não ajuda a encontrar a informação, pois a partilha em muito poucos contâineres excessivamente "genéricos". Além disso, é tecnicamente falho ao incluir a categoria "outros" dentro de cada subcategoria, contrariando as boas práticas da ciência da informação e do bom senso.

Se querem usar um vocabulário de boa qualidade que ainda é mantido regularmente, que inclusive é multilíngue e oferece dados processáveis por máquina, sugiro o [Eurovoc](http://eurovoc.europa.eu/drupal/?q=pt).

**Comment by caduvieira** [comment]
Não tem pt_BR pela minha procura.
Por exemplo: Fabrico industrial  - http://eurovoc.europa.eu/3632
Controlo de produção - http://eurovoc.europa.eu/179

O Outros da subcategoria é 'Outros de <categoria>' como em : Outros de
Saúde, Outros em Saneamento ...

Tem algum documento sobre essas boas práticas que possa compartilhar?

Em 20 de agosto de 2015 09:33, Augusto Herrmann notifications@github.com
escreveu:

**Comment by augusto-herrmann** [comment]
Sim, esses são exemplos de 'outros de <categoria>'.

É possível que o assunto seja tratado na [ISO 25964-1](http://www.iso.org/iso/catalogue_detail.htm?csnumber=53657), mas não tenho conferir pois para ter acesso à norma é preciso comprá-la.

O que tenho documentado é que essa foi uma das críticas levantadas por especialistas em ciência da informação que trabalham no governo durante a consulta pública de 2013 e o problema tem sido ignorado desde então. Acredito que esse tenha sido um dos motivos que levaram à cessação da participação de especialistas no tema nos grupos de trabalho do VCGE.

Sobre a questão de haver apenas o português de Portugal, seria sim um certo obstáculo num primeiro momento mas não impede a compreensão do significado. Do ponto de vista da experiência do usuário, esse fato é mais que compensado pela maior pulverização dos termos em maior quantidade e em mais níveis, o que facilita a encontrar a informação.

Se fo o caso, é possível fazer testes com ambos os esquemas de classificação - Eurovoc e VCGE - e ver com qual o usuário encontra a informação com mais facilidade. Minha aposta é com o Eurovoc.

**Comment by kchnr** [comment]
Por enquanto, para fins de consistência, vamos trabalhar na conversão, para manter atualizado com o VCGE mais recente. 

Mas essas sugestões são legais, então criamos o cartão #22 para discutir sobre isso.

**Comment by kchnr** [comment]
Sobre este cartão especificamente, o commit com a tabela de conversão: https://github.com/servicosgovbr/cartas-de-servico/commit/94f8f8a97b5448027dd87f7046096696b4cee996

Para fazer a conversão:
- Vale notar que as alterações no "servico.xsd" foram revertidas (https://github.com/servicosgovbr/cartas-de-servico/commit/90de7da9dbd657dd4760ba029cc827136916e76f), pois dependem desta conversão, caso contrário os testes vão falhar no snap.
- Substituir os itens VCGE-1 para os itens VCGE-2
- Itens da coluna VCGE-1, mesmo se contiverem "," são um item único (alguns termos legado continham ",")
- Itens da coluna VCGE-2 são listas separados por ","
- Se o item do xml legado não existir no VCGE-1, deve simplesmente ser removido
- Itens VCGE-1 que correspondem a um VCGE-2 vazio, também devem ser removidos

**Comment by caduvieira** [comment]
Vocab na versão 2.0.3 tem os dcterms:replaces de conversão do 1.x.x para o
2.x.x

Até onde eu vi todos os termos do vcge 1 tinham correspondentes no 2.

**Comment by nitaibezerra** [comment]
Quero expor minha preocupação com essa Issue. Faço coro com o Augusto quanto à falsa percepção de melhoria com a troca da versão do VCGE. Também participei do processo que originou a versão mais recente. Foi um processo pouco transparente e muito centralizado.
O VCGE-2 é raso e tem problemas estruturais, como já relatado pelo @augusto-herrmann. 

Para além disso acredito que não exista normativo que obrigue os sistemas a atualizarem a versão do VCGE utilizada. Partindo dessa premissa, acho extremamente válida um reflexão técnica quanto ao valor que se está agregando ao projeto Portal de Serviços resolvendo essa Issue.

@caduvieira, ter um subtermo com um conceito de "Outros" não agrega valor ao recurso marcado com esse termo. Para esses casos, o recurso/documento deve sermarcado com o termo mais amplo, já que nenhum termo filho consegue restringir melhor.

**Comment by caduvieira** [comment]
Entendi sobre o Outros. Beleza.

Em 21 de agosto de 2015 11:40, Nitai Bezerra da Silva <
notifications@github.com> escreveu:

**Comment by rslyra** [comment]
Bom dia. 
Alguns esclarecimentos sobre o VCGE 2.0: 
- o VCGE, embora tenha o nome de vocabulário, é mais uma lista de categorias do que um vocabulário propriamente dito. Isso é coerente com o ePMG, origem do VCGE, que prevê usar o VCGE como categorias e um outro conjunto de termos como palavras chaves. 
- SEMPRE incentivamos que órgãos (ou sistemas) específicos criem vocabulários específicos, que o VCGE não irá atender nesse grau de detalhe. Isso poe ser usado nas palavras chaves. 
- Sobre o processo de mudança, horários de reunião, grupo de discussão, etc, está tudo em http://governoeletronico.gov.br/acoes-e-projetos/e-ping-padroes-de-interoperabilidade/vcge.
- O VCGE é inspirado na Portaria 42 (MTO) e COFOG. 
  Temos algumas novidades, como um esforço de alinhamento com o PPA, mas creio que esse não seja o lugar. Eu sou o responsável pelo VCGE e estou a disposição para dúvidas, propostas, etc.

**Comment by cv** [comment]
https://github.com/servicosgovbr/editor-de-servicos/issues/294#issuecomment-136690708

**Comment by cv** [comment]
Nossa migração para o VCGE2 vai seguir uma estratégia híbrida por um tempo. Após a decisão de utilizar o VCGE2 sem as categorias "Outros em…", dei uma olhada nas categorias do VCGE1 que eram utilizadas nos serviços existentes:
- Abastecimento
- Administração financeira
- Agricultura orgânica
- Agropecuária
- Alimento
- Ambiente e saúde
- Comunicações
- Comércio e Serviços
- Economia e Finanças
- Educação
- Educação básica
- Educação superior
- Educação à distância
- Emergências e Urgências
- Encargos financeiros
- Esporte e Lazer
- Finanças
- Habitação
- Humanização na saúde
- Indústria
- Meio ambiente
- Pecuária
- Pessoa
- Previdência Social
- Profissionais da educação
- Proteção social
- Qualidade ambiental
- Relações Internacionais
- Saúde
- Saúde da criança
- Saúde da família
- Saúde da mulher
- Saúde do homem
- Saúde do idoso
- Saúde dos portadores de deficiências
- Segurança e Ordem Pública
- Trabalho
- Transportes
- Turismo
- Urbanismo

Algumas delas se repetem no VCGE2, e as que não se repetem vão ser mantidas como estão, mas iremos forçar o servidor a recategorizar o serviço para o VCGE2 antes de conseguir publicar uma atualização a um serviço que use categorias da VCGE1.

**Comment by cv** [comment]
Este trabalho será feito no cartão https://github.com/servicosgovbr/editor-de-servicos/issues/294 (e parte das recomendações acima também veio de comentários naquele cartão).
