### ISSUE TITLE
Importar cartas hospedadas externamente

### ISSUE THREAD

**Issue by cv** [servicosgovbr/cartas-de-servico#24]
Alguns órgãos gostariam de hospedar suas próprias cartas.

Para evitar confusão e manter tudo centralizado, o ideal seria ter algo rodando de tempos em tempos com uma lista de URLs configurável que baixasse as cartas disponíveis nessas URLs e as adicionasse / alterasse no repositório de cartas.

**Comment by sahrosa** [comment]
Cartão duplicado com #395
