### ISSUE TITLE
Atualizar repositório de cartas a cada x tempo

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/cartas-de-servico#27]
Para atualizar tanto editor quanto portal.

@krchr, se quiser pode complementar o cartão.

**Comment by cv** [comment]
No Editor, temos que atualizar o repositório (pull com strategy theirs) ao abrir um serviço (caso ele tenha sido editado por outra instância do Editor).

No Portal, isso já foi feito pela #406.
